# Generated by Django 3.2 on 2023-04-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230403_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(null=True, related_name='titles', to='reviews.Genre', verbose_name='Жанр'),
        ),
    ]
